version: '3.8' 

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    container_name: auth-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: authServer
      MONGO_INITDB_ROOT_PASSWORD: devpassword
    ports:
      - 27017:27017
    volumes:
      - ./mongodb-data:/data/db

  mongo:
    build: ./
    environment:
      MONGO_INITDB_ROOT_USERNAME: authServer
      MONGO_INITDB_ROOT_PASSWORD: devpassword
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27018
    ports:
      - '27018:27018'
